# Generated by Django 4.1.7 on 2023-03-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('AUTHOR', 'AUTHOR')], default='AUTHOR', max_length=16),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
