# Generated by Django 4.1.7 on 2023-03-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_content_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
    ]
